# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-28 17:29
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=12)),
                ('genero', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=1)),
                ('sisben', models.CharField(max_length=12)),
                ('transporte', models.CharField(choices=[('S', 'si'), ('N', 'no')], max_length=1)),
                ('direccion', models.CharField(max_length=60)),
                ('familias', models.CharField(choices=[('S', 'si'), ('N', 'no')], max_length=1)),
                ('alimentacion', models.CharField(choices=[('S', 'si'), ('N', 'no')], max_length=1)),
                ('desplazado', models.CharField(choices=[('S', 'si'), ('N', 'no')], max_length=1)),
                ('contacto', models.CharField(max_length=12)),
                ('nacimiento', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=30)),
                ('credo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CentrosSena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centroSena', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Colegios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colegio', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=30)),
                ('asignatura', models.CharField(max_length=50)),
                ('contacto', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Estrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrato', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=12)),
                ('carrera', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=1)),
                ('sisben', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=60)),
                ('contacto', models.CharField(max_length=12)),
                ('nacimiento', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=30)),
                ('estrato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proyecto.Estrato')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrato', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Inst_educativas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Institucion_educativa',
                'verbose_name_plural': 'Inst_educativas',
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=30)),
                ('sexo', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sisben',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Universidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universidad', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Veredas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vereda', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='inst_educativas',
            name='rector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Usuario'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='estrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proyecto.Estrato'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proyecto.Grado'),
        ),
    ]
