# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-28 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioEstimulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipoDocumento', models.CharField(max_length=10)),
                ('documentoOtro', models.CharField(max_length=30)),
                ('documento', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=30)),
                ('edad', models.CharField(max_length=30)),
                ('estadoCivil', models.CharField(max_length=30)),
                ('cabezaFamilia', models.CharField(max_length=30)),
                ('hijos', models.CharField(max_length=10)),
                ('pertenencia', models.CharField(max_length=30)),
                ('pertenenciaOtro', models.CharField(max_length=50)),
                ('direccionEstudiante', models.CharField(max_length=100)),
                ('ciudadEstudiante', models.CharField(max_length=150)),
                ('barrioEstudiante', models.CharField(max_length=150)),
                ('ubicacionEstudiante', models.CharField(max_length=30)),
                ('vivienda', models.CharField(max_length=30)),
                ('estrato', models.CharField(max_length=30)),
                ('sisben', models.CharField(max_length=30)),
                ('nucleoFamiliar', models.CharField(max_length=30)),
                ('direccionPadres', models.CharField(max_length=100)),
                ('ciudadPadres', models.CharField(max_length=150)),
                ('barrioPadres', models.CharField(max_length=150)),
                ('ubicacionPadres', models.CharField(max_length=30)),
                ('serviciosPublicos', models.CharField(max_length=70)),
                ('dependenciaEconomica', models.CharField(max_length=30)),
                ('dependenciaOtro', models.CharField(max_length=50)),
                ('ingresosFamilia', models.CharField(max_length=30)),
                ('colegio', models.CharField(max_length=150)),
                ('oficialPrivado', models.CharField(max_length=30)),
                ('anoTerminacion', models.CharField(max_length=30)),
                ('actaGrado', models.CharField(max_length=50)),
                ('universidad', models.CharField(max_length=150)),
                ('centrosSena', models.CharField(max_length=150)),
                ('sede', models.CharField(max_length=50)),
                ('acreditacionUniversidad', models.CharField(max_length=30)),
                ('carrera', models.CharField(max_length=100)),
                ('tecnicaTecnologica', models.CharField(max_length=30)),
                ('acreditacionCarrera', models.CharField(max_length=30)),
                ('cicloEducacion', models.CharField(max_length=30)),
                ('semestreEnCurso', models.CharField(max_length=30)),
                ('modalidad', models.CharField(max_length=30)),
                ('modalidadOtro', models.CharField(max_length=50)),
                ('propedeutico', models.CharField(max_length=30)),
                ('propedeuticoOtro', models.CharField(max_length=50)),
                ('valorMatricula', models.CharField(max_length=30)),
                ('beneficiarioprogramas', models.CharField(max_length=30)),
                ('programaOtro', models.CharField(max_length=50)),
                ('incentivoEducativo', models.CharField(max_length=30)),
                ('cuantasVeces', models.CharField(max_length=30)),
                ('extraAcademicas', models.CharField(max_length=30)),
                ('extraAcademicaPaga', models.CharField(max_length=30)),
                ('parentesco1', models.CharField(max_length=100)),
                ('parentesco2', models.CharField(max_length=100)),
                ('parentesco3', models.CharField(max_length=100)),
                ('parentesco4', models.CharField(max_length=100)),
                ('parentesco5', models.CharField(max_length=100)),
                ('parentesco6', models.CharField(max_length=100)),
                ('parentesco7', models.CharField(max_length=100)),
                ('totalObtenido', models.CharField(max_length=100)),
            ],
        ),
    ]
