# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-07-18 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='horas',
            name='nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.FormularioEstimulos'),
        ),
    ]
