# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-16 06:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20170719_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='traza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('tipo', models.CharField(max_length=1)),
                ('tiempo', models.DateTimeField(default=datetime.datetime.now)),
                ('accion', models.TextField()),
            ],
        ),
    ]
