# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-16 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_traza'),
    ]

    operations = [
        migrations.DeleteModel(
            name='traza',
        ),
    ]
