# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-20 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_traza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=20)),
                ('grado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Grado')),
            ],
        ),
        migrations.CreateModel(
            name='SedeInstitucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='inst_educativas',
            options={},
        ),
        migrations.RemoveField(
            model_name='inst_educativas',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='inst_educativas',
            name='rector',
        ),
        migrations.AlterField(
            model_name='inst_educativas',
            name='direccion',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='inst_educativas',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='sedeinstitucion',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Inst_educativas'),
        ),
    ]
