# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-09 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_auto_20170819_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inst_educativas2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
    ]
