# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-09 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_inst_educativas2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedeInstitucion2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=50)),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Inst_educativas2')),
            ],
        ),
    ]
