# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-09 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0012_sedeinstitucion2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=20)),
                ('grado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Grado')),
            ],
        ),
    ]
