# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-09 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0013_grupos2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('documento', models.CharField(max_length=12)),
                ('genero', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=1)),
                ('transporte', models.CharField(choices=[('S', 'si'), ('N', 'no')], max_length=1)),
                ('direccion', models.CharField(max_length=60)),
                ('familias', models.CharField(choices=[('S', 'si'), ('N', 'no')], max_length=1)),
                ('alimentacion', models.CharField(choices=[('S', 'si'), ('N', 'no')], max_length=1)),
                ('desplazado', models.CharField(choices=[('S', 'si'), ('N', 'no')], max_length=1)),
                ('contacto', models.CharField(max_length=12)),
                ('nacimiento', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=30)),
                ('credo', models.CharField(max_length=25)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proyecto.Grado')),
            ],
        ),
    ]
