# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-14 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0015_auto_20170914_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno2',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Inst_educativas2'),
        ),
        migrations.AlterField(
            model_name='alumno2',
            name='procedencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.Veredas'),
        ),
        migrations.AlterField(
            model_name='alumno2',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.SedeInstitucion2'),
        ),
    ]
