# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-14 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_auto_20170914_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno2',
            name='alimentacion',
            field=models.CharField(choices=[('S', 'si'), ('N', 'no')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno2',
            name='contacto',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno2',
            name='desplazado',
            field=models.CharField(choices=[('S', 'si'), ('N', 'no')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno2',
            name='documento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno2',
            name='familias',
            field=models.CharField(choices=[('S', 'si'), ('N', 'no')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno2',
            name='genero',
            field=models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno2',
            name='nacimiento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno2',
            name='transporte',
            field=models.CharField(choices=[('S', 'si'), ('N', 'no')], max_length=20),
        ),
    ]
