# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-29 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0018_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(max_length=500),
        ),
    ]
